/**
 * Represents a communication channel within the application.
 */
export interface Channel {
  id: string;
  name?: string;
  description?: string;
  createdBy: string;
  createdAt: Date;
  members: string[];
  updatedAt: Date;
  isPrivate: boolean;
}


/**
 * Represents a new channel to be created.
 * Excludes the `id` property, which is typically generated by the system.
 */
export type NewChannel = Omit<Channel, 'id'>;